### Forward Propagation & Backpropagation

In [1]:
import torch

---

Initialization: A simple neural net with 4 input neurons, 1 hidden layer with 3 neurons and 1 output neuron

In [2]:
n_input = 4
n_neurons_hidden_one = 3
n_output = 1

In [3]:
X = torch.tensor([[0.9], [0.8], [0.7], [0.6]])
W1 = torch.rand(n_input, n_neurons_hidden_one)
W2 = torch.rand(n_neurons_hidden_one, n_output)

In [12]:
print(f'Input sample data with 4 features (4x1):\n{X}\n')
print(f'First weight matrix (4x3):\n{W1}\n')
print(f'Second weight matrix (3x1):\n{W2}\n')

Input sample data with 4 features (4x1):
tensor([[0.9000],
        [0.8000],
        [0.7000],
        [0.6000]])

First weight matrix (4x3):
tensor([[0.6915, 0.2038, 0.1092],
        [0.8664, 0.2407, 0.9444],
        [0.9586, 0.5905, 0.4535],
        [0.4292, 0.7313, 0.8132]])

Second weight matrix (3x1):
tensor([[0.9415],
        [0.9888],
        [0.9888]])



Forward Propagation

In [14]:
def sigmoid(z):
    return 1 / (1 + torch.exp(-z))

In [15]:
Z = W1.t().matmul(X) 
H = sigmoid(Z) 
O = H.t().matmul(W2)
Y_cap = sigmoid(O)

In [22]:
print(f'Initial output from the randomly initialized weights:\n{Y_cap}')

Initial output from the randomly initialized weights:
tensor([[0.9203]])


Error Calculation

In [24]:
Y = 0
E = torch.pow(Y - Y_cap, 2)
print(f'Initial error:\n{E}')

Initial error:
tensor([[0.8470]])


Backpropagation

In [26]:
def sigmoid_grad(x):
    return x * (1 - x)

In [27]:
dE_dY_cap = -2 * (Y - Y_cap)
dY_cap_dO = sigmoid_grad(Y_cap)
dO_dW2 = H

dE_dW2 = dE_dY_cap * dY_cap_dO * dO_dW2

In [32]:
print(f'Gradient of weight matrix two w.r.t error:\n{dE_dW2}')

Gradient of weight matrix two w.r.t error:
tensor([[0.1220],
        [0.1044],
        [0.1134]])


In [28]:
dO_dH = W2
dH_dZ = sigmoid_grad(H)
dZ_dW1 = X

dE_dW1 = dE_dW2 * dO_dH * dH_dZ * dZ_dW1.t()

In [34]:
print(f'Gradient of weight matrix one w.r.t error:\n{dE_dW1.t()}')

Gradient of weight matrix one w.r.t error:
tensor([[0.0090, 0.0163, 0.0136],
        [0.0080, 0.0145, 0.0120],
        [0.0070, 0.0127, 0.0105],
        [0.0060, 0.0109, 0.0090]])


Parameter Updation

In [29]:
W2_new = W2 - 0.1 * dE_dW2
W1_new = W1 - 0.1 * dE_dW1.t()

Forward propapagtion with updated weights

In [30]:
Z = W1_new.t().matmul(X) 
H = sigmoid(Z) 
O = H.t().matmul(W2_new)
Y_cap = sigmoid(O)

In [31]:
print(f'New output from updated set of weights:\n{Y_cap}')

New output from updated set of weights:
tensor([[0.9181]])
